In [1]:
import numpy as np
import scipy.stats
import scipy.spatial
from sklearn.model_selection import KFold
import random
from sklearn.metrics import mean_squared_error
from math import sqrt
import math
import warnings
import sys
#from sklearn.utils.extmath import np.dot

warnings.simplefilter("error")

users = 4
items = 5
X=np.arange(0,6)
def readingFile(filename):
    f = open(filename,"r")
    data = []
    for row in f:
        r = row.split(',')
        e = [int(r[0]), int(r[1]), int(r[2])]
        data.append(e)
    return data

def similarity_user(data):
    print ("Hello User 1")
    #f_i_d = open("sim_user_based.txt","w")
    user_similarity_cosine = np.zeros((users,users))
    user_similarity_jaccard = np.zeros((users,users))
    user_similarity_pearson = np.zeros((users,users))
    for user1 in range(users):
        print (user1)
        for user2 in range(users):
            if np.count_nonzero(data[user1]) and np.count_nonzero(data[user2]):
                user_similarity_cosine[user1][user2] = 1-scipy.spatial.distance.cosine(data[user1],data[user2])
                user_similarity_jaccard[user1][user2] = 1-scipy.spatial.distance.jaccard(data[user1],data[user2])
                try:
                    if not math.isnan(scipy.stats.pearsonr(data[user1],data[user2])[0]):
                        user_similarity_pearson[user1][user2] = scipy.stats.pearsonr(data[user1],data[user2])[0]
                    else:
                        user_similarity_pearson[user1][user2] = 0
                except:
                    user_similarity_pearson[user1][user2] = 0

            #f_i_d.write(str(user1) + "," + str(user2) + "," + str(user_similarity_cosine[user1][user2]) + "," + str(user_similarity_jaccard[user1][user2]) + "," + str(user_similarity_pearson[user1][user2]) + "\n")
    #f_i_d.close()
    return user_similarity_cosine, user_similarity_jaccard, user_similarity_pearson

recommend_data = readingFile("test.csv")

similarity_user(recommend_data)


Exception ignored in: <_io.FileIO name='test.csv' mode='rb' closefd=True>
Traceback (most recent call last):
  File "<ipython-input-1-fafdae2c8764>", line 51, in <module>


Hello User 1
0
1
2
3


(array([[1.        , 0.8819171 , 0.73854895, 0.99339927],
        [0.8819171 , 1.        , 0.93048421, 0.92615842],
        [0.73854895, 0.93048421, 1.        , 0.78258558],
        [0.99339927, 0.92615842, 0.78258558, 1.        ]]),
 array([[1.        , 0.33333333, 0.33333333, 0.        ],
        [0.33333333, 1.        , 0.33333333, 0.        ],
        [0.33333333, 0.33333333, 1.        , 0.33333333],
        [0.        , 0.        , 0.33333333, 1.        ]]),
 array([[ 1.        ,  0.2773501 , -0.5       ,  0.94491118],
        [ 0.2773501 ,  1.        ,  0.69337525,  0.57655666],
        [-0.5       ,  0.69337525,  1.        , -0.18898224],
        [ 0.94491118,  0.57655666, -0.18898224,  1.        ]]))

In [ ]:
import pandas as pd

dict1 = {'age':10,
            'gender':1,
            'height':1,
            'weight':1,
            'ap_hi':1,
            'ap_lo':1,
            'cholesterol':1,
            'gluc':1,
            'smoke':1,
            'alco':1,
            'active':1}
           
dff=pd.DataFrame(dict1,index=[0])

finaldff=dff[['gender','cholesterol','smoke','alco','active']]

In [ ]:
df1=pd.read_csv('ratings.csv',sep=',',error_bad_lines=False)

print(len(df1))
print(df1)
df=df1#.sample(n=1000,replace=True)
X = df.iloc[:,:-2].values # We drop our "target" feature and use all the remaining features in our dataframe to train the model.
y = df.iloc[:,2].values

In [ ]:
X

In [ ]:
y

In [ ]:
X1 = X # We drop our "target" feature and use all the remaining features in our dataframe to train the model.
y1 = y

In [ ]:
import numpy as np
from scipy.spatial import distance
ycount=0
rowcount=0
countsofsys=0
y_actu=[]
y_pred=[]

for row in X1:
    outexpect=[]
    overall=[]
    print(row)
    rowcount+=1
    print('row count is ',rowcount)
    listofall=[]
    
    
    expected=y1[ycount]
    ycount+=1    

    countis=0
    for row1 in X1:
            y=row
            summation = 0
            print('check1')
            y_bar=row1
            print('check11',y_bar,'second is',y)
            #if y!=y_bar:
            print('check2')
            n = len(y) #finding total number of items in list
            for i in range (0,n):  #looping through each element of the list
                difference = y[i] - y_bar[i]  #finding the difference between observed and predicted value
                squared_difference = difference**2  #taking square of the differene 
                summation = summation + squared_difference  #taking a sum of all the differences
            MSE = summation/n  #dividing summation by total values to obtain average
            print("The Mean Square Error is: " , MSE)
            dst = distance.euclidean(y, y_bar)
            print("dst is: " , dst)
            if dst<0.02:
                outexpect.append(1.0)
            else:
                outexpect.append(0.0)
            if MSE<=0.5:
                outexpect.append(1.0)
            else:
                outexpect.append(0.0)
            #if len(outexpect)>len(X1):
            if len(outexpect)>10:
                break
    #outexpect.append(valis)
    y_actu.append(expected)
    valmax=max(outexpect,key=outexpect.count)
    #outexpect
    overall.append(valmax)
    print('from the logic',valmax)
    
    valis=1.0
    if valmax==1.0 and valis==1.0:
        valis=1.0
    if valmax==1.0 and valis==0.0:
        valis=0.0

    y_pred.append(valis)    
overallcorrect=countsofsys/(len(X1))
print('overallcorrect ',overallcorrect)   



In [ ]:
import numpy as np
from scipy.spatial import distance
import pandas as pd
import pickle
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
listofcol='age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active'.split(',')
#listofcolumns=['age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio']


import pandas as pd
import pickle
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

def proposedlogic(finaldff):
    threshold=0.50
    df1=pd.read_csv('ratings.csv',sep=',',error_bad_lines=False)

    print(len(df1))
    print(df1)
    df=df1#.sample(n=1000,replace=True)
    X = df.iloc[:,:-1].values # We drop our "target" feature and use all the remaining features in our dataframe to train the model.
    y = df.iloc[:,11].values

    X = df[['gender','cholesterol','smoke','alco','active']] # here we have 2 variables for multiple regression. If you just want to use one variable for simple linear regression, then use X = df['Interest_Rate'] for example.Alternatively, you may add additional variables within the brackets
    Y = df['cardio']
    X1 = X.iloc[:,:].values # We drop our "target" feature and use all the remaining features in our dataframe to train the model.
    X2=finaldff.iloc[:,:].values
    outexpect=[]
    overall=[]
    for row in X2:
        countis=0
        for row1 in X1:
            print(row1)
            y=row
            summation = 0
            print('check1')
            y_bar=row1
            print('check11',y_bar,'second is',y)
            #if y!=y_bar:
            print('check2')
            n = len(y) #finding total number of items in list
            for i in range (0,n):  #looping through each element of the list
                difference = y[i] - y_bar[i]  #finding the difference between observed and predicted value
                squared_difference = difference**2  #taking square of the differene 
                summation = summation + squared_difference  #taking a sum of all the differences
            MSE = summation/n  #dividing summation by total values to obtain average
            print("The Mean Square Error is: " , MSE)
            dst = distance.euclidean(y, y_bar)
            print("dst is: " , dst)
            if dst<0.02:
                outexpect.append(1.0)
            else:
                outexpect.append(0.0)
            if MSE<=0.5:
                outexpect.append(1.0)
            else:
                outexpect.append(0.0)
            #outexpect+=1
            #if len(outexpect)>len(X1):
            if len(outexpect)>10:
                break
    #outexpect.append(valis)
    #y_actu.append(expected)
    valmax=max(outexpect,key=outexpect.count)
    #outexpect
    overall.append(valmax)
    print('from the logic',valmax)
    return valmax
    #print(val,valis)
    

proposedlogic(finaldff)